title: "VMR.ahk"
description: "AutoHotkey wrapper class for Voicemeeter Remote API"
remote_theme: pmarsceill/just-the-docs
baseurl: "/VMR.ahk"
url: "https://saifaqqad.github.io"
permalink: pretty
search_enabled: true
aux_links:
  "VMR.ahk on GitHub":
    - "//github.com/SaifAqqad/VMR.ahk"
back_to_top: false
