title: "VMR.ahk"
description: "AutoHotkey wrapper class for Voicemeeter Remote API"
remote_theme: pmarsceill/just-the-docs
permalink: pretty
search_enabled: true
aux_links:
  "VMR.ahk on GitHub":
    - "//github.com/SaifAqqad/VMR.ahk"
last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p"
